<?php
/**
 * @file
 * Defines a CCK field for source code with GeSHi syntax highlighting.
 *
 * @todo: is the GeSHi CSS file always loaded when needed?
 */

/**
 * Implements hook_theme().
 */
function geshifield_theme() {
  return array(
    'geshifield_default' => array(
      'function' => 'geshifield_formatter_default',
      'render element' => 'geshifield',
    ),
  );
}

function geshifield_formatter_default($variables) {
  $language = $variables['geshifield']['#language'];
  $sourcecode = $variables['geshifield']['#sourcecode'];
  $output = '';
  module_load_include('inc', 'geshifilter', 'geshifilter.pages');
  if ($sourcecode) {
    $output .= geshifilter_geshi_process($sourcecode, $language);
  }
  $elements = array();
  $elements[] = array(
    '#markup' => $output,
  );
  return render($elements);
}
